server:
  port: 8080

spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    mode: HTML
  datasource:
    url: jdbc:mysql://rm-j6c2k7uyo6n6o2870no.mysql.rds.aliyuncs.com:3306/course-selection-system?useSSL=false
    username: slx
    password: slx_9920
#    url: jdbc:mysql://localhost:3306/course-selection-system?useSSL=false
#    username: root
#    password: 2000516
    driver-class-name: com.mysql.cj.jdbc.Driver

